#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : WALinuxAgent
Version  : 2.2.53.1
Release  : 83
URL      : https://github.com/Azure/WALinuxAgent/archive/v2.2.53.1/WALinuxAgent-2.2.53.1.tar.gz
Source0  : https://github.com/Azure/WALinuxAgent/archive/v2.2.53.1/WALinuxAgent-2.2.53.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: WALinuxAgent-autostart = %{version}-%{release}
Requires: WALinuxAgent-bin = %{version}-%{release}
Requires: WALinuxAgent-data = %{version}-%{release}
Requires: WALinuxAgent-license = %{version}-%{release}
Requires: WALinuxAgent-python = %{version}-%{release}
Requires: WALinuxAgent-python3 = %{version}-%{release}
Requires: WALinuxAgent-services = %{version}-%{release}
Requires: distro
Requires: pyasn1
BuildRequires : buildreq-distutils3
BuildRequires : distro
BuildRequires : distro-python3
BuildRequires : pyasn1
Patch1: 0001-Fix-waagent-error-caused-in-ClearLinuxDeprovisionHan.patch

%description
# Microsoft Azure Linux Agent
## Develop branch status
[![Travis CI](https://travis-ci.org/Azure/WALinuxAgent.svg?branch=develop)](https://travis-ci.org/Azure/WALinuxAgent/branches)
[![CodeCov](https://codecov.io/gh/Azure/WALinuxAgent/branch/develop/graph/badge.svg)](https://codecov.io/gh/Azure/WALinuxAgent/branch/develop)

%package autostart
Summary: autostart components for the WALinuxAgent package.
Group: Default

%description autostart
autostart components for the WALinuxAgent package.


%package bin
Summary: bin components for the WALinuxAgent package.
Group: Binaries
Requires: WALinuxAgent-data = %{version}-%{release}
Requires: WALinuxAgent-license = %{version}-%{release}
Requires: WALinuxAgent-services = %{version}-%{release}

%description bin
bin components for the WALinuxAgent package.


%package data
Summary: data components for the WALinuxAgent package.
Group: Data

%description data
data components for the WALinuxAgent package.


%package license
Summary: license components for the WALinuxAgent package.
Group: Default

%description license
license components for the WALinuxAgent package.


%package python
Summary: python components for the WALinuxAgent package.
Group: Default
Requires: WALinuxAgent-python3 = %{version}-%{release}
Provides: walinuxagent-python

%description python
python components for the WALinuxAgent package.


%package python3
Summary: python3 components for the WALinuxAgent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the WALinuxAgent package.


%package services
Summary: services components for the WALinuxAgent package.
Group: Systemd services

%description services
services components for the WALinuxAgent package.


%prep
%setup -q -n WALinuxAgent-2.2.53.1
cd %{_builddir}/WALinuxAgent-2.2.53.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617902567
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/WALinuxAgent
cp %{_builddir}/WALinuxAgent-2.2.53.1/LICENSE.txt %{buildroot}/usr/share/package-licenses/WALinuxAgent/861181924d993ee58a17a2c3c3a3faecf895849c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/bin/waagent2.0
rm -f %{buildroot}/usr/sbin/waagent
rm -f %{buildroot}/usr/sbin/waagent2.0
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
ln -s ../waagent.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/waagent.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/waagent.service

%files bin
%defattr(-,root,root,-)
/usr/bin/waagent

%files data
%defattr(-,root,root,-)
/usr/share/defaults/waagent/waagent.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/WALinuxAgent/861181924d993ee58a17a2c3c3a3faecf895849c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/waagent.service
/usr/lib/systemd/system/waagent.service
